-- MySQL Script generated by MySQL Workbench
-- Sat 29 Apr 2023 11:44:05 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `training_id` INT NOT NULL,
  PRIMARY KEY (`id`, `training_id`),
  INDEX `fk_course_training1_idx` (`training_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_training1`
    FOREIGN KEY (`training_id`)
    REFERENCES `mydb`.`training` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course_date` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course_date` (
  `id` INT NOT NULL,
  `course_date` DATE NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_id`),
  INDEX `fk_course_date_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_date_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_date_has_teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course_date_has_teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course_date_has_teacher` (
  `user_id` INT NOT NULL,
  `course_date_id` INT NOT NULL,
  `course_date_course_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `course_date_id`, `course_date_course_id`),
  INDEX `fk_course_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_course_has_teacher_course_date1_idx` (`course_date_id` ASC, `course_date_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_has_teacher_course_date1`
    FOREIGN KEY (`course_date_id` , `course_date_course_id`)
    REFERENCES `mydb`.`course_date` (`id` , `course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course_material` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course_material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `file` VARCHAR(45) NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_id`),
  INDEX `fk_course_material_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_material_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`training` ;

CREATE TABLE IF NOT EXISTS `mydb`.`training` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `training_category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `training_category_id`),
  INDEX `fk_training_training_category1_idx` (`training_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_training_training_category1`
    FOREIGN KEY (`training_category_id`)
    REFERENCES `mydb`.`training_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`training_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`training_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`training_has_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`training_has_student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`training_has_student` (
  `training_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`training_id`, `user_id`),
  INDEX `fk_training_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_training_has_user_training_idx` (`training_id` ASC) VISIBLE,
  CONSTRAINT `fk_training_has_user_training`
    FOREIGN KEY (`training_id`)
    REFERENCES `mydb`.`training` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_training_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_has_attendance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_has_attendance` (
  `id` INT NOT NULL,
  `presence` TINYINT NOT NULL,
  `course_date_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_date_id`, `user_id`),
  INDEX `fk_user_has_attendance_course_date1_idx` (`course_date_id` ASC) VISIBLE,
  INDEX `fk_user_has_attendance_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_attendance_course_date1`
    FOREIGN KEY (`course_date_id`)
    REFERENCES `mydb`.`course_date` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_attendance_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
